ls:
  .js: kebab-case
  .md: kebab-case
  .ts: kebab-case
  .d.ts: kebab-case
  .spec.ts: kebab-case
  .generated.ts: kebab-case

ignore:
  - babel.config.js
  - .cache
  - .eslintrc.js
  - .git
  - .github/ISSUE_TEMPLATE
  - .github/PULL_REQUEST_TEMPLATE.md
  - dist
  - jest.config.ts
  - node_modules
  - SECURITY.md
  - test/e2e/node_modules
  - config.example.js
  - README.md
